# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
      POSTGRES_DB: test_app
      #POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  db2:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test_app
      MYSQL_USER: todo
      MYSQL_PASSWORD: todo
    ports:
      - "3307:3306"
