# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test_app
      MYSQL_USER: todo
      MYSQL_PASSWORD: todo
    ports:
      - "3307:3306"

  todo-app:
    image: todo-app:0.0.1-SNAPSHOT
    restart: always
    ports:
      - "8080:8080"
